#Faça um programa que armazene em um dicionário os dados de um funcionário de uma empresa, compostos de: Nome, Idade, Sexo (M/F), CPF, Data de Nascimento, Código do Setor onde trabalha (0-99), Cargo que ocupa (string de até 30 caracteres) e Salário. Os dados devem ser digitados pelo usuário, armazenados no dicionário e exibidos na tela.
funcionario=dict()
funcionario['nome']=str(input())
funcionario['idade'] = int(input())
funcionario['sexo'] = str(input()).upper()
funcionario['cpf'] = str(input())
funcionario['nascimento'] = str(input())
funcionario['setor'] = int(input())
funcionario['cargo'] = str(input())
funcionario['salario'] =float(input())
print(funcionario)